name: description-based-point-cloud-quality-assessment
channels:
  - conda-forge
dependencies:
  - cython==3.0.5
  - python==3.10.0
  - pip==23.3.1
  - gcc==13.2.0 
  - gxx==13.2.0
  - gfortran==13.2.0
  - tbb==2021.10.0
  - libxcrypt==4.4.36
  - opencv==4.9.0
  - pip:
      - -r requirements.txt

